apiVersion: v1
kind: Service
metadata:
  name: crypto-monitor-service
  namespace: default
spec:
  selector:
    app: crypto-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
