apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: default
type: Opaque
stringData:
  # Database
  POSTGRES_PASSWORD: "your-super-secret-and-long-postgres-password"
  
  # JWT
  JWT_SECRET: "your-super-secret-jwt-token-at-least-32-chars-long"
  ANON_KEY: "replace-with-your-anon-key"
  SERVICE_ROLE_KEY: "replace-with-your-service-role-key"
  
  # Realtime
  REALTIME_ENC_KEY: "your-super-secret-realtime-encryption-key"
  
  # Connection Strings
  DATABASE_URL: "postgres://supabase_admin:your-super-secret-and-long-postgres-password@supabase-db:5432/postgres"
  GOTRUE_DB_DATABASE_URL: "postgres://supabase_auth_admin:your-super-secret-and-long-postgres-password@supabase-db:5432/postgres"
  PGRST_DB_URI: "postgres://authenticator:your-super-secret-and-long-postgres-password@supabase-db:5432/postgres"
